-- $ sqlite3 users.db < users.sql

PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS Profiles;

DROP TABLE IF EXISTS Users;


CREATE TABLE Users(
    User_id INTEGER primary key NOT NULL,
    UserName VARCHAR NOT NULL,
    PassWord VARCHAR NOT NULL,
    UNIQUE(UserName)

);
INSERT INTO users(UserName,PassWord) VALUES
("DANH","123"),
("CONG","123"),
("PHAM","123");

CREATE TABLE Profiles(
  PROFILE_ID INT(10) NOT NULL  PRIMARY KEY,
  PUSER_ID INT(10)  NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(150),
  COUNTRY VARCHAR(250),
  ZIPCODE VARCHAR(100),
  CITY VARCHAR(100),
  STREET VARCHAR(100),
  STATE CHAR(10),

  FOREIGN KEY (PUSER_ID) REFERENCES Users(User_id),
  UNIQUE (FIRST_NAME , LAST_NAME )

); 
INSERT INTO Profiles(PUSER_ID,FIRST_NAME,LAST_NAME,COUNTRY,ZIPCODE,CITY,STREET,STATE) VALUES
(1, 'DANH', 'PHAM', 'USA', '12345', 'FULLERTON', '123 MAIN ST', 'CA'),
(2, 'ANH', 'PHAM', 'USA', '54321', 'WESMINSTER', '456 BLVD', 'TX'),
(3, 'HIEN', 'PHAM', 'USA', '12345', 'FULLERTON', '123 MAIN ST', 'CA');
COMMIT;
