root: python3 -m bottle --bind=localhost:$PORT --debug --reload root
userServices: python3 -m bottle --bind=localhost:$PORT --debug --reload user
ProjectServices: python3 -m bottle --bind=localhost:$PORT --debug --reload project
TeamServices: python3 -m bottle --bind=localhost:$PORT --debug --reload team
